name: Git Release

on:
  push:
    tags:
    - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Moving build to dist-directory
        run: ./copyFilesToDist.sh
        shell: bash
      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME_PREFIX: "Release "
        with:
          args: |
            dist/wahooMapsCreator-release*.zip
            darwin-amd64.zip
            linux-amd64.zip
            windows-amd64.zip